### ISSUE TITLE
Setup Notes

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notes-android#1644]
With transferring Android notes to Nextcloud, we want to change some things

- [x] change remaining leftovers (e.g. Maintainer)
- [x] design notes on Monday
- [x] check that team can build Notes app
- [x] Stefan to contributor #1655
- [x] adjust labels
- [x] add ci
- [x] add to config transfer, etc. https://github.com/nextcloud/android-config/pull/40
- [x] check that SSO still works
- [x] setup fastlane #1669
       - [  ]  release RC
- [ ] release new on Huawei AppGallery
- fix bugs
  - [x] [Material 3 dialogs with input fields on small screens are not functional](https://github.com/nextcloud/notes-android/issues/1660), emulator Nexus One 3,7" https://github.com/nextcloud/notes-android/pull/1689
  - [ ] [Data loss when opening note from a widget](https://github.com/stefan-niedermann/nextcloud-notes/issues/1379)
  - [ ] [Notes visible behind biometric prompt](https://github.com/stefan-niedermann/nextcloud-notes/issues/927)

Design review
- [x] change icon: https://fonts.google.com/icons?selected=Material+Icons:edit: #1666 
- [x] about -> credits #1655
    - Maintainer: Nextcloud
    - Developers: Stefan Niedermann (founder), with existing link

Main UI:
- [ ] copy menu entries to three dots menu in list view
- [ ] grid mode: bottom right "three dots menu"

**Comment by AlvaroBrey** [comment]
Random question: do we want to make the first official release 4.0, instead of 3.8?

**Comment by AlvaroBrey** [comment]
> * change icon: https://fonts.google.com/icons?selected=Material+Icons:edit:

Is this gonna be changed in server as well? Right now server has the same icon as the app

**Comment by tobiasKaminsky** [comment]
Yes, server will also change. 
Jan wanted to create an issue on their repo.
